# Automatically generated by configure
PREFIX=/mingw
libdir=/mingw/lib
incdir=/mingw/include/sys
AR=x86_64-w64-mingw32-ar
CC=x86_64-w64-mingw32-gcc
RANLIB=x86_64-w64-mingw32-ranlib
STRIP=x86_64-w64-mingw32-strip
BUILD_STATIC=yes
BUILD_MSVC=
LIBCMD=echo ignoring lib
